# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: younhwan <younhwan@student.42seoul.kr>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/01 00:07:28 by younhwan          #+#    #+#              #
#    Updated: 2022/08/01 00:54:25 by younhwan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = lib_my_own.a

CC = cc
CFLAGS = -Wall -Wextra -Werror
AR = ar rcs
RM = rm -f

LIBFT_DIR = ./libft
FT_PRINTF_DIR = ./ft_printf
GNL_DIR = ./get_next_line

